"""
Exporter — bundles project artifacts into a portable summary.

Formats:
  markdown  — single docs/project_summary.md combining all docs
  zip       — archive of docs/, src/, and .vibecraft/manifest.json
"""

import json
import zipfile
from datetime import datetime, timezone
from pathlib import Path

from rich.console import Console

console = Console()


class Exporter:
    def __init__(self, project_root: Path):
        self.root     = project_root
        self.docs_dir = project_root / "docs"
        self.src_dir  = project_root / "src"
        self.vc_dir   = project_root / ".vibecraft"

    # ------------------------------------------------------------------

    def export_markdown(self) -> Path:
        """Combine all documentation into a single readable markdown file."""
        manifest = self._load_manifest()
        parts: list[str] = []

        # Header
        parts.append(f"# {manifest.get('project_name', 'Project')} — Complete Summary")
        parts.append(
            f"\n> Generated by Vibecraft Export  |  "
            f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}\n"
        )

        # Table of contents placeholder
        parts.append("---\n")

        # Append all docs in logical order
        doc_order = [
            ("Research",        self.docs_dir / "research.md"),
            ("Stack",           self.docs_dir / "stack.md"),
            ("Architecture",    self.docs_dir / "design" / "architecture.md"),
            ("Data Flow",       self.docs_dir / "design" / "data_flow.md"),
            ("Sequences",       self.docs_dir / "design" / "sequence.md"),
        ]

        for title, path in doc_order:
            if path.exists():
                parts.append(f"\n---\n\n## {title}\n")
                parts.append(path.read_text(encoding="utf-8"))

        # Phase plans
        plans_dir = self.docs_dir / "plans"
        if plans_dir.exists():
            plan_files = sorted(plans_dir.glob("phase_*.md"))
            if plan_files:
                parts.append("\n---\n\n## Implementation Plans\n")
                for pf in plan_files:
                    parts.append(f"\n### {pf.stem.replace('_', ' ').title()}\n")
                    parts.append(pf.read_text(encoding="utf-8"))

        # Source code index
        if self.src_dir.exists():
            src_files = [
                f for f in sorted(self.src_dir.rglob("*"))
                if f.is_file() and not any(
                    part.startswith(".") for part in f.parts
                )
            ]
            if src_files:
                parts.append("\n---\n\n## Source Code Index\n")
                for sf in src_files:
                    rel = sf.relative_to(self.root)
                    suffix = sf.suffix.lstrip(".")
                    parts.append(f"\n### `{rel}`\n")
                    parts.append(f"```{suffix}\n{sf.read_text(encoding='utf-8', errors='replace')}\n```\n")

        content  = "\n".join(parts)
        out_path = self.docs_dir / "project_summary.md"
        out_path.write_text(content, encoding="utf-8")

        console.print(f"[green]✓[/green] Exported → [cyan]{out_path.relative_to(self.root)}[/cyan]")
        return out_path

    # ------------------------------------------------------------------

    def export_zip(self) -> Path:
        """Create a zip archive with docs/, src/, and manifest.json."""
        manifest   = self._load_manifest()
        name       = manifest.get("project_name", "vibecraft_project").replace(" ", "_").lower()
        ts         = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        zip_name   = f"{name}_{ts}.zip"
        zip_path   = self.root / zip_name

        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            # docs/
            for f in sorted(self.docs_dir.rglob("*")):
                if f.is_file():
                    zf.write(f, f.relative_to(self.root))

            # src/
            if self.src_dir.exists():
                for f in sorted(self.src_dir.rglob("*")):
                    if f.is_file():
                        zf.write(f, f.relative_to(self.root))

            # manifest
            manifest_path = self.vc_dir / "manifest.json"
            if manifest_path.exists():
                zf.write(manifest_path, Path(".vibecraft") / "manifest.json")

        console.print(f"[green]✓[/green] Exported → [cyan]{zip_name}[/cyan]")
        return zip_path

    # ------------------------------------------------------------------

    def _load_manifest(self) -> dict:
        manifest_path = self.vc_dir / "manifest.json"
        if manifest_path.exists():
            try:
                return json.loads(manifest_path.read_text(encoding="utf-8"))
            except Exception:
                pass
        return {}
